### ISSUE TITLE
503 on npm-registry-cors-proxy.herokuapp.com

### ISSUE THREAD

**Issue by tlvince** [npm/semver.npmjs.com#5]
It looks like http://npm-registry-cors-proxy.herokuapp.com is down:

```
❯ curl -I http://npm-registry-cors-proxy.herokuapp.com
HTTP/1.1 503 Service Unavailable
Connection: keep-alive
Server: Cowboy
Date: Mon, 17 Aug 2015 19:21:02 GMT
Content-Length: 484
Content-Type: text/html; charset=utf-8
Cache-Control: no-cache, no-store
```

On http://semver.npmjs.com itself, the error is reported as:

```
[Error] XMLHttpRequest cannot load http://npm-registry-cors-proxy.herokuapp.com/lodash. Origin http://semver.npmjs.com is not allowed by Access-Control-Allow-Origin. (semver.npmjs.com, line 0)
Sorry, could not load data.
```

**Comment by zeke** [comment]
Hi @tlvince. Thanks for reporting. That proxy app is running on Heroku's free service, which as of a few months ago idles at least a few hours per day. Unfortunately neither I nor @linclark are employed by npm any more, so it's unlikely that this will be resolved any time soon. That said, I see a few ways to fix this, in order of preference.

1. Add your two cents to https://github.com/npm/npm-registry-couchapp/issues/108 -- this issue has been open for over two years.
1. Submit a PR to this repo that uses http://cors.maxogden.com/ as a proxy instead of the Heroku app. I would ask @maxogden first if it's okay with him.
1. Nag me to pay $7/month to keep the Heroku proxy up all the time. :)

**Comment by maxogden** [comment]
you can run your own cors proxy by deploying https://github.com/Rob--W/cors-anywhere, thats what I do. please don't use my cors proxy, I don't guarantee any uptime

**Comment by ashleygwilliams** [comment]
am working with @mmalecki who is going to fix the CORS issue using haproxy.
